"""initial migration

Revision ID: 7a05afa2e19a
Revises: 38c4e85512a9
Create Date: 2016-11-17 18:20:36.561660

"""

# revision identifiers, used by Alembic.
revision = '7a05afa2e19a'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
